name: Compilar Mi Sys Play

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Compilar Sysmodule
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    steps:

      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Comprobar entorno
        run: |
          echo "DEVKITPRO=$DEVKITPRO"
          echo "DEVKITA64=$DEVKITA64"
          make --version
          aarch64-none-elf-g++ --version

      - name: Limpiar
        run: |
          make clean || true

      - name: Compilar
        run: |
          make

      - name: Comprobar archivos
        run: |
          echo "===== ARCHIVOS ====="
          find . -maxdepth 2 -type f \
            \( -name "*.elf" -o -name "*.nso" -o -name "*.npdm" -o -name "*.nsp" \) \
            -print

      - name: Subir NSP
        uses: actions/upload-artifact@v4
        with:
          name: mi-sys-play
          path: |
            mi_sys_play.nsp
            mi_sys_play.nso
            mi_sys_play.npdm
            mi_sys_play.elf
